# copy and paste this code in google colab notebook and train the network
# read processed_metadata file from google drive, train rl_model
# -*- coding: utf-8 -*-
"""google_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8jE2s54F387x7-Q9m0r34U95j0O9J7c
"""

# Mount Google Drive
from google.colab import drive

drive.mount('/content/drive')

# Install necessary libraries (if not already installed)
# !pip install pandas torch torchvision tqdm scikit-learn

# Import libraries
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import logging
import time

# Import the DQN model and ExperienceStore from the files you uploaded to google drive
# These two files should be in the google drive folder
import sys

sys.path.append('/content/drive/MyDrive/strategies/RL')  # path to the folder with the files
from network import DQN  # Import the DQN model from network.py
from experience_store import ExperienceStore  # Import ExperienceStore
from process_metadata import MetadataProcessor  # Import the MetadataProcessor

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logging.info(f"Using device: {device}")


# --- Helper Functions (mostly from rl_trainer.py) ---
def train_model(model, target_model, metadata_processor, optimizer, experience_store, device, batch_size, gamma,
                num_episodes, model_save_path, initial_train_df):
    """
    Trains the DQN model in batches over multiple episodes.

    Args:
        model (nn.Module): The DQN model.
        target_model (nn.Module): The target DQN model.
        metadata_processor (MetadataProcessor): The MetadataProcessor instance.
        optimizer (optim.Optimizer): Optimizer.
        experience_store (ExperienceStore): The experience store.
        device (str): Device to train on ('cuda' or 'cpu').
        batch_size (int): Batch size for training.
        gamma (float): Discount factor.
        num_episodes (int): Number of episodes to train for.
        model_save_path (str): The path to save the model weights.
        initial_train_df (pd.DataFrame): The initial training data.
    """
    criterion = nn.MSELoss()
    logging.info("Starting training...")
    train_df = initial_train_df.copy()  # create copy of the initial dataframe.

    for episode in tqdm(range(num_episodes)):
        logging.info(f"Starting episode {episode + 1}/{num_episodes}")
        episode_start_time = time.time()
        total_reward = 0
        episode_experiences = []

        # Process metadata for each episode
        metadata_processing_start_time = time.time()

        # If it's the first episode, pass None (initial processing), otherwise, pass the train_df
        if episode == 0:
            processed_metadata = metadata_processor.process_metadata_for_episode()
        else:
            processed_metadata = metadata_processor.process_metadata_for_episode(df=train_df)

        metadata_processing_end_time = time.time()
        logging.info(
            f"Metadata processing time for episode {episode + 1}: {metadata_processing_end_time - metadata_processing_start_time:.4f} seconds")

        if processed_metadata is None:
            logging.warning(f"Processed metadata is None, skipping episode {episode + 1}.")
            continue

        # save the train_df
        train_df = processed_metadata.copy()  # Save the current processed metadata as the next input.

        for i in range(len(processed_metadata)):
            logging.debug(f"Processing row {i + 1}/{len(processed_metadata)} in episode {episode + 1}")
            state_image = torch.tensor(processed_metadata.loc[i, 'image_tensor']).to(device)
            state_numerical_data = torch.tensor(processed_metadata.loc[i, 'numerical_data_normalized']).to(device)
            action = processed_metadata.loc[i, 'action']
            reward = processed_metadata.loc[i, 'reward']
            target_q = processed_metadata.loc[i, 'target_q']

            # next state is in the next row
            if i < len(processed_metadata) - 1:
                next_state_image = torch.tensor(processed_metadata.loc[i + 1, 'image_tensor']).to(device)
                next_state_numerical_data = torch.tensor(processed_metadata.loc[i + 1, 'numerical_data_normalized']).to(
                    device)
                done = False
            else:
                next_state_image = torch.empty(1, 320, 320).to(device)
                next_state_numerical_data = torch.empty(1, 17).to(device)
                done = True

            total_reward += reward

            # Save experience to a list to add all of them to the store after going through one episode
            episode_experiences.append(((state_image, state_numerical_data), action, reward,
                                        (next_state_image, next_state_numerical_data), done))

        # Push all episode experiences to the memory at once
        logging.debug(f"Pushing {len(episode_experiences)} experiences to memory for episode {episode + 1}")
        for experience in episode_experiences:
            experience_store.push(*experience)

        # Training step (now outside of the loop over rows)
        if len(experience_store) >= batch_size:
            num_training_batches = len(experience_store) // batch_size
            logging.info(f"Starting {num_training_batches} training batches for episode {episode + 1}")
            for batch_num in range(num_training_batches):

                # get training data
                batch_data = experience_store.sample(batch_size)
                if batch_data is None:
                    logging.warning(f"Skipping training batch due to insufficient data in episode {episode + 1}")
                    continue  # skip this loop if we have not enough data.

                state_images, state_numerical_data, action_batch, reward_batch, next_state_images, next_state_numerical_data, done_batch = batch_data

                # Check for empty tensors after sampling. This can happen if there are not enough transitions in the buffer
                if len(state_images) == 0 or len(state_numerical_data) == 0 or len(next_state_images) == 0 or len(
                        next_state_numerical_data) == 0:
                    logging.warning(f"Skipping training batch due to empty tensors in episode {episode + 1}")
                    continue  # skip this loop if we have empty tensors.

                # If we have an empty tensors we do not want to process them, so skip this loop.
                if len(state_images) != batch_size or len(next_state_images) != batch_size:
                    logging.warning(f"Skipping training batch due to incorrect batch size in episode {episode + 1}")
                    continue

                state_images = state_images.to(device)
                state_numerical_data = state_numerical_data.to(device)
                next_state_images = next_state_images.to(device)
                next_state_numerical_data = next_state_numerical_data.to(device)
                action_batch = action_batch.to(device)
                reward_batch = reward_batch.to(device)
                done_batch = done_batch.to(device)

                # calculate target values
                with torch.no_grad():
                    next_q_values = target_model(next_state_images, next_state_numerical_data).max(1)[0]
                    target_q_values = reward_batch + (
                                gamma * next_q_values * (~done_batch))  # (~done_batch) is same as (1- done_batch)

                # get q values
                q_values = model(state_images, state_numerical_data).gather(1, action_batch.unsqueeze(1)).squeeze(1)

                # back prop
                loss = criterion(q_values, target_q_values)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

        # update target network
        if episode % 10 == 0:
            logging.info(f"Updating target model at episode {episode + 1}")
            target_model.load_state_dict(model.state_dict())

        logging.info(f"Finished episode {episode + 1}/{num_episodes}, total reward: {total_reward}")

        # Save model weights after each episode
        torch.save(model.state_dict(), model_save_path)
        logging.info(f"Model weights saved to {model_save_path}")

        episode_end_time = time.time()
        logging.info(f"Total time for episode {episode + 1}: {episode_end_time - episode_start_time:.4f} seconds")


# --- End Helper Functions ---

def main():
    """Main function for training the model on Google Colab."""
    # --- Define Paths in Google Drive ---
    drive_root = "/content/drive/MyDrive/strategies/RL"  # Adjust this to your Google Drive path
    processed_metadata_file = os.path.join(drive_root,
                                           "processed_metadata_episode1.csv")  # The file that will be uploaded from your local computer
    model_save_path = os.path.join(drive_root, "model_weights_colab.pth")

    # --- Hyperparameters ---
    num_episodes = 10
    batch_size = 32
    learning_rate = 0.001
    num_actions = 3
    gamma = 0.99
    replay_buffer_capacity = 10000
    transaction_cost_percent = 0.001
    epsilon_start = 1.0
    epsilon_end = 0.01
    epsilon_decay = 0.995

    # --- Load Processed Metadata from Google Drive ---
    logging.info(f"Loading processed metadata from: {processed_metadata_file}")
    try:
        metadata_df = pd.read_csv(processed_metadata_file)
        # Convert string list representations back to tensors
        metadata_df['image_tensor'] = metadata_df['image_tensor'].apply(
            eval)  # Converts string lists back to actual lists
        metadata_df['image_tensor'] = metadata_df['image_tensor'].apply(torch.tensor)  # converts list to tensors
        metadata_df['numerical_data_normalized'] = metadata_df['numerical_data_normalized'].apply(
            eval)  # Converts string lists back to actual lists
        metadata_df['numerical_data_normalized'] = metadata_df['numerical_data_normalized'].apply(
            torch.tensor)  # converts list to tensors
        logging.info("Metadata loaded successfully.")
    except Exception as e:
        logging.error(f"Error loading metadata: {e}")
        return

    # Split data into train and test
    train_df, test_df = train_test_split(metadata_df, test_size=0.2, shuffle=False)

    # --- Model, Optimizer, Experience Store ---
    logging.info("Creating model, target model, optimizer, and ExperienceStore...")
    model = DQN(num_actions).to(device)
    target_model = DQN(num_actions).to(device)
    target_model.load_state_dict(model.state_dict())
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    experience_store = ExperienceStore(replay_buffer_capacity,
                                       os.path.join(drive_root, "experience_store.pkl"))  # Save to google drive.

    # Create metadata processor
    logging.info("Creating MetadataProcessor...")
    metadata_processor = MetadataProcessor(model_path=model_save_path, device=device,
                                           transaction_cost_percent=transaction_cost_percent,
                                           epsilon_start=epsilon_start,
                                           epsilon_end=epsilon_end, epsilon_decay=epsilon_decay)

    # Load model weights if they exist in google drive
    if os.path.exists(model_save_path):
        model.load_state_dict(torch.load(model_save_path, map_location=device))
        logging.info(f"Model weights loaded from {model_save_path}")
    else:
        logging.info("No saved model weights found. Starting with a new model.")

    # --- Train the Model ---
    train_model(model, target_model, metadata_processor, optimizer, experience_store, device, batch_size, gamma,
                num_episodes, model_save_path, train_df)

    logging.info("Training completed.")


if __name__ == "__main__":
    main()
